name: Deployment pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches: [master]
    types: [opened, synchronize]

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      
      - name: npm install 
        run: npm install  
      
      - name: lint
        run: npm run eslint
      
      - name: build
        run: npm run build
      
      - name: Notify Slack build fail
        uses: 8398a7/action-slack@v3.9.0
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took # selectable (default: repo,message)
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
        if: ${{ failure() && false }}

      - name: test
        run: npm run test
      
      - name: e2e tests
        uses: cypress-io/github-action@v2
        with:
          command: npm run test:e2e
          start: npm run start-prod
          wait-on: http://localhost:3001

      - name: deploy
        if: ${{ github.event_name == 'push' && false &&
          contains(join(env.COMMIT_MESSAGES, ','), '#skip') == false }}
        uses: akhileshns/heroku-deploy@v3.11.10
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "mooc-fso2020-part11-phonebook"
          heroku_email: "markus.erapolku@gmail.com"
          healthcheck: "https://mooc-fso2020-part11-phonebook.herokuapp.com/health"
          checkstring: "ok"
          delay: 5
          rollbackonhealthcheckfailed: true
        env:
          COMMIT_MESSAGES: ${{ toJson(github.event.commits.*.message) }}
      
      - name: Notify Slack deploy success
        uses: 8398a7/action-slack@v3.9.0
        with:
          status: custom
          fields: workflow,job,commit,repo,ref,author,took
          custom_payload: |
            {
              attachments: [{
                color: '${{ job.status }}' === 'success' ? 'good' : '${{ job.status }}' === 'failure' ? 'danger' : 'warning',
                text: `a new version deployed to ${process.env.AS_REPO} (${process.env.AS_COMMIT}) by ${process.env.AS_AUTHOR}, took ${process.env.AS_TOOK}`,
              }]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
        if: ${{ success() }}
        
      - name: Bump version and push tag
        if: ${{ github.event_name == 'push' && false &&
          contains(join(env.COMMIT_MESSAGES, ','), '#skip') == false }}
        uses: anothrNick/github-tag-action@1.33.0
        env:
          COMMIT_MESSAGES: ${{ toJson(github.event.commits.*.message) }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
        